kind: Deployment
apiVersion: apps/v1
metadata:
  name: react-docker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-docker
  template:
    metadata:
      labels:
        app: react-docker
    spec:
      containers:
      - name: react-docker
        image: ujinslav/gitops01:6439f232b03ceebf90ce65c34efc84cac02cb990
        ports:
        - containerPort: 80
